//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOL.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public int ID_AUDITORIA { get; set; }
        public string USUARIO { get; set; }
        public string ACCION { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public string VALOR_ANTERIOR { get; set; }
        public string VALOR_NUEVO { get; set; }
        public System.DateTime FECHA { get; set; }
    }
}
