//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOL.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_LIBRO
    {
        public int ID_LIBRO { get; set; }
        public string NOMBRE_LIBRO { get; set; }
        public string AUTOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<short> FK_GENERO { get; set; }
        public short FK_ESTADO { get; set; }
        public string IMAGEN { get; set; }
        public string PDF { get; set; }
    
        public virtual CAT_ESTADO CAT_ESTADO { get; set; }
        public virtual CAT_GENERO CAT_GENERO { get; set; }
    }
}
