//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOL.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        public int ID_COMPRA { get; set; }
        public int FK_LIBRO { get; set; }
        public int FK_USUARIO { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
    
        public virtual CAT_LIBRO CAT_LIBRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
