//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoOL.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTA
    {
        public int ID_MULTA { get; set; }
        public int FK_PRESTAMO { get; set; }
        public System.DateTime FECHA_MULTA { get; set; }
        public int VALOR_MULTA { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
